version: '3'
services:
  s1:
    build:
      context: ./s1
    ports:
      - "3001:8081"
    networks:
      - mynetwork
  s2:
    build:
      context: ./s2
    ports:
      - "3002:8082"
    networks:
      - mynetwork
  s3:
    build:
      context: ./s3
    ports:
      - "3003:8083"
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
